#!/usr/bin/env python

txt = open('DefaultKeyBinding.dict').read()
txt = txt.replace('"\UF710"', '"\U00A7"') # make delete the compose key instead of F13
txt = txt.replace('"\U007E"', '"\\\\~"') # fix compose key codes which use tilde
open('DefaultKeyBinding.dict', 'w').write(txt)
